### ISSUE TITLE
Issues with Gazebo after running the update step

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/test_repo_robond_robotic_arm_pick_and_place#2]
I updated Gazebo to 7.7 based on the instructions. I am currently working with the older vmdk so updating based on these commands seemed easier.

But after updating, I tried to run the following, from the lessons -
```
roslaunch simple_arm robot_spawn.launch
```

Gazebo starts with the environment and the robot, but I get the following -

![image](https://cloud.githubusercontent.com/assets/12501638/26532454/d7543a9e-441e-11e7-9cc3-03c0663784e7.png)

I am not sure what the issue is here. I am still looking into it but thought you might have more experience here. [I'll download the latest vm, but would like to figure this out just in case and would appreciate some input]

**Comment by sahiljuneja** [comment]
cc - @hvpandya, @ryan-keenan

**Comment by hvpandya** [comment]
@sahiljuneja Can you restart the system and try again? Sometimes version upgrades leave behind broken symbolic links which are only resolved at boot.

**Comment by sahiljuneja** [comment]
I did do that initially, no luck. 

Shouldn't there be any associated updates for ROS Gazebo as well? I though there were ROS specific packages for Gazebo as well.

**Comment by hvpandya** [comment]
@sahiljuneja was your problem resolved by moving to the new VM?

**Comment by sahiljuneja** [comment]
Yeah, it was. Everything seems fine on the new VM, so I don't think there's any need to worry about the above issue with the old one for the time being. I'll close this. Thanks!
