### ISSUE TITLE
Troubles getting all the objects loaded.

### ISSUE THREAD

**Issue by bpinaya** [udacity/test_repo_robond_robotic_arm_pick_and_place#3]
Hey there, someone when I run this in demo mode. I am not seeing all the Gazebo models.
![screenshot from 2017-06-04 23 19 57](https://cloud.githubusercontent.com/assets/2473733/26769395/a2bc98e0-497c-11e7-96b0-b602de8c5bea.png)
The Rviz seems to be showing them though.
![screenshot from 2017-06-04 23 18 15](https://cloud.githubusercontent.com/assets/2473733/26769401/ae3ab6f2-497c-11e7-8498-879955f2fd8d.png)

**Comment by hvpandya** [comment]
Closing this issue, since docker is not officially supported.
